### ISSUE TITLE
colin MVP: 0.1.0 release checklist

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/colin#77]
Let's collaborate on a 0.1.0 release definition of colin. Please edit this post when adding more items.

* [x] colin is packaged as RPM #64
* [x] colin can be installed at least from copr https://copr.fedorainfracloud.org/coprs/phracek/colin/ see the latest build https://copr.fedorainfracloud.org/coprs/phracek/colin/builds/ #64 
* [x] documentation is up #69
* [x] all checks are documented http://colin.readthedocs.io/en/latest/list_of_checks.html
* [x] we have some unit and integration tests and they are passing #63
* [x] CI is set up (this is a tough one but we need it)
* [x] we have pretty output #65 

stretch goal:

* [x] we have contributing.md #71 
* [x] colin is part of Fedora

What do you think?

**Comment by phracek** [comment]
Part of the PR #64 includes building colin as RPM and soon I will add a COPR repository for `colin`

**Comment by phracek** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1572084
https://src.fedoraproject.org/rpms/colin

**Comment by phracek** [comment]
All issues are done. Closing it.

**Comment by TomasTomecek** [comment]
oh wow!
